apiVersion: apps/v1
kind: Deployment
metadata:
  name: conference
  labels:
    app: conference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conference
  template:
    metadata:
      labels:
        app: conference
    spec:
      containers:
        - name: conference
          image: username/conference:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5